// Generated by LiveScript 1.5.0
(function(){
  var Applicative;
  module.exports = new (Applicative = (function(){
    Applicative.displayName = 'Applicative';
    var return_, prototype = Applicative.prototype, constructor = Applicative;
    Applicative.prototype.return_ = return_ = function(x){
      return function(){
        return x;
      };
    };
    Applicative.prototype['return'] = return_;
    function Applicative(){}
    return Applicative;
  }()));
}).call(this);
