// Generated by LiveScript 1.5.0
(function(){
  var when_, Option;
  when_ = require('./flow').when_;
  module.exports = new (Option = (function(){
    Option.displayName = 'Option';
    var may, prototype = Option.prototype, constructor = Option;
    Option.prototype.may = may = when_(function(it){
      return it != null;
    });
    function Option(){}
    return Option;
  }()));
}).call(this);
